### ISSUE TITLE
Integration CI broken for python lib `juju==2.9.5`

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kubeflow-volumes-operator#17]
[Integration CI runs](https://github.com/canonical/kubeflow-volumes-operator/runs/4458737197?check_suite_focus=true#step:4:125) are failing when doing:

```
async def test_build_and_deploy(ops_test):
    ...
    await ops_test.model.deploy("cs:istio")
```
raising the error:
```
____________________________ test_build_and_deploy _____________________________
Traceback (most recent call last):
  File "/home/runner/work/kubeflow-volumes-operator/kubeflow-volumes-operator/tests/integration/test_charm.py", line 28, in test_build_and_deploy
    await ops_test.model.deploy("cs:istio")
  File "/home/runner/work/kubeflow-volumes-operator/kubeflow-volumes-operator/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 1610, in deploy
    res = await self.deploy_types[str(url.schema)].resolve(url, architecture, application_name, channel, series, entity_url)
  File "/home/runner/work/kubeflow-volumes-operator/kubeflow-volumes-operator/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 510, in resolve
    series = self.get_series(entity_url, result)
  File "/home/runner/work/kubeflow-volumes-operator/kubeflow-volumes-operator/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 1551, in _get_series
    ss = entity['Meta']['supported-series']
KeyError: 'supported-series'
```

This has not been debugged, but has instead been mitigated by pinning libjuju to the last known working version `juju==2.9.3` in `tox.ini`.  This should be properly fixed or a bug raised against juju

**Comment by DomFleischmann** [comment]
This should be addressed by now with the latest releases
